### ISSUE TITLE
Broken STM32F4xx clock configuration

### ISSUE THREAD

**Issue by kasjer** [apache/mynewt-core#2193]
Commit 5cc9e6910045d425f813496f3c2eb2e047237dfb (Add initial STM32WBxx MCU support) introduced error in clock configuration that can result in infinite loop during system startup.

Culprit is partially uninitialized variable RCC_OscInitTypeDef osc_init in SystemClock_Config().
Few fields in osc_init.PLL are not initialized and when osc_init.PLL.PLLState will happen to be 2
HAL_RCC_OscConfig() will try to configure PLL with other values from PLL variable that are uninitialized and that will result in infinite loop waiting for PLL to become ready while it never happen due to wrong parameters.

I'm not sure what is correct fix for this but having
osc_init.PLL.PLLState = RCC_PLL_NONE;
fixes the problem for me.

I home this will be easy for you Fabio

**Comment by utzig** [comment]
There's a few strange things, one is that the code probably was wrongly added by me since it's unrelated to stm32wb55 so it was in some pre-release stage I think; another interesting thing is that I don't seem to have issues with stm32f7 initialization which I would expect to since it's very similar to stm32f4 clocking system. I have submitted an early fix as you suggested with #2208 (works for me!), but I might updated it again in the near future...
